'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import QRCode from 'qrcode';
type Item={id:string;media_type:'image'|'video';caption:string|null;status:'pending'|'approved'|'rejected';created_at:string};
const GalleryVideo=dynamic(()=>import('./gallery-video'),{ssr:false,loading:()=> <span className="gallery-media-loading">Loading video…</span>});
const Icon=({name}:{name:'camera'|'upload'|'admin'|'gallery'|'check'|'back'|'trash'})=><span aria-hidden="true" className="icon">{{camera:'◉',upload:'↑',admin:'◆',gallery:'▦',check:'✓',back:'←',trash:'×'}[name]}</span>;
function Brand(){return <div className="brand" aria-label="SingShot"><b>SING</b><i>SHOT</i><small>THE LONDON KARAOKE CLUB</small></div>}
function Disco(){return <div className="disco-wrap" aria-hidden="true"><div className="disco"/><div className="beam b1"/><div className="beam b2"/></div>}
function CustomerQR({compact=false}:{compact?:boolean}){const [src,setSrc]=useState('');useEffect(()=>{QRCode.toDataURL(`${location.origin}/`,{width:compact?132:220,margin:1,color:{dark:'#10091c',light:'#fff9e9'}}).then(setSrc)},[compact]);return <div className={`customer-qr ${compact?'compact':''}`}>{src?<img src={src} alt="QR code to open SingShot on a phone"/>:<span className="qr-loading">Loading QR…</span>}<div><b>SCAN TO SINGSHOT</b><small>Open camera · Tap the link</small></div></div>}
export default function Home(){const [view,setView]=useState<'landing'|'capture'|'preview'|'success'|'admin'|'gallery'>('landing');const [file,setFile]=useState<File|null>(null);const [url,setUrl]=useState('');const [caption,setCaption]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
useEffect(()=>{const sync=()=>{const path=location.pathname.replace(/\/+$/,'')||'/';setView(path==='/staff'?'admin':path==='/gallery'?'gallery':'landing')};sync();addEventListener('popstate',sync);return()=>removeEventListener('popstate',sync)},[]);
useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
function navigate(next:'landing'|'admin'|'gallery',path:string){history.pushState({},'',path);setView(next)}
function choose(f?:File){if(!f)return;setError('');if(!f.type.startsWith('image/')&&!f.type.startsWith('video/')){setError('Please choose a photo or video.');return}if(url)URL.revokeObjectURL(url);setFile(f);setUrl(URL.createObjectURL(f));setView('preview')}
async function submit(){if(!file)return;setBusy(true);setError('');const d=new FormData();d.set('media',file);d.set('caption',caption);d.set('consent',String(consent));try{const r=await fetch('/api/submissions',{method:'POST',body:d});const j=await r.json();if(!r.ok)throw new Error(j.error);setView('success')}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
function reset(){setFile(null);setUrl('');setCaption('');setConsent(false);setError('');navigate('landing','/')}
if(view==='admin')return <Admin onBack={()=>navigate('landing','/')} onGallery={()=>navigate('gallery','/gallery')}/>;
if(view==='gallery')return <Gallery onBack={()=>navigate('admin','/staff')}/>;
return <main className="guest"><header className="top"><Brand/><button className="admin-link" onClick={()=>navigate('admin','/staff')}><Icon name="admin"/> Admin</button></header>
{view==='landing'&&<section className="landing"><Disco/><div className="hero-copy"><p className="eyebrow">YOUR MOMENT. THEIR SCREEN.</p><h1>Sing it.<br/><em>Snap it.</em><br/>Share it.</h1><p className="intro">Capture your karaoke high note and join tonight’s live wall of fame.</p><button className="primary start" onClick={()=>setView('capture')}>Start SingShot <span>→</span></button><p className="micro">Photo or short video · Staff approved</p></div><CustomerQR compact/></section>}
{view==='capture'&&<section className="flow"><button className="back" onClick={()=>setView('landing')}><Icon name="back"/> Back</button><div className="panel"><span className="step">01 / CAPTURE</span><h1>Catch the<br/><em>moment.</em></h1><p>Take a photo, shoot a short clip, or pick one you already love.</p>{error&&<div className="error" role="alert">{error}</div>}<div className="capture-actions"><button className="capture-card pink" onClick={()=>{if(input.current){input.current.setAttribute('capture','environment');input.current.click()}}}><Icon name="camera"/><b>Open camera</b><small>Photo or short video</small></button><button className="capture-card purple" onClick={()=>{if(input.current){input.current.removeAttribute('capture');input.current.click()}}}><Icon name="upload"/><b>Choose a file</b><small>From your device</small></button></div><input ref={input} className="sr-only" aria-label="Choose photo or video" type="file" accept="image/jpeg,image/png,image/webp,image/heic,video/mp4,video/webm,video/quicktime" onChange={e=>choose(e.target.files?.[0])}/><p className="limits">Photos up to 12 MB · Videos up to 25 MB</p></div></section>}
{view==='preview'&&<section className="flow"><button className="back" onClick={()=>setView('capture')}><Icon name="back"/> Retake</button><div className="preview-grid"><div className="media-preview">{file?.type.startsWith('video/')?<video src={url} controls playsInline/>:<img src={url} alt="Your selected SingShot preview"/>}<span>PREVIEW</span></div><div className="panel preview-panel"><span className="step">02 / MAKE IT YOURS</span><h1>Looking<br/><em>iconic.</em></h1><label>Caption <small>OPTIONAL</small><textarea maxLength={160} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="What’s the anthem tonight?"/><span className="count">{caption.length}/160</span></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I'm happy for The London Karaoke Club to share this moment on its social channels. <small>Optional</small></span></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" disabled={busy} onClick={submit}>{busy?'Sending to the stage…':'Submit SingShot →'}</button></div></div></section>}
{view==='success'&&<section className="success"><div className="success-mark"><Icon name="check"/></div><span className="eyebrow">YOU'RE IN THE QUEUE</span><h1>That was<br/><em>electric.</em></h1><p>Your SingShot is with our crew. Once approved, it’ll light up the live gallery.</p><button className="primary" onClick={reset}>Capture another →</button><button className="text-btn" onClick={()=>navigate('gallery','/gallery')}>See the live gallery</button></section>}</main>}
function Admin({onBack,onGallery}:{onBack:()=>void;onGallery:()=>void}){const [items,setItems]=useState<Item[]>([]);const [status,setStatus]=useState('all');const [media,setMedia]=useState('all');const [selected,setSelected]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [authed,setAuthed]=useState(false);const [checking,setChecking]=useState(true);const [pin,setPin]=useState('');
async function load(silent=false){if(!silent)setLoading(true);try{const r=await fetch(`/api/submissions?status=${status}&media=${media}`,{cache:'no-store'});if(!r.ok)throw 0;setItems((await r.json()).submissions);setError('')}catch{setError('Could not refresh submissions.')}finally{setLoading(false)}}useEffect(()=>{if(!authed)return;load();const t=setInterval(()=>load(true),10000);return()=>clearInterval(t)},[status,media,authed]);
useEffect(()=>{fetch('/api/staff-session').then(r=>setAuthed(r.ok)).finally(()=>setChecking(false))},[]);
async function login(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/staff-login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});if(r.ok){setAuthed(true);setLoading(true);load()}else setError('That staff passcode is not correct.')}
async function act(id:string,action:'approved'|'rejected'|'delete'){const r=await fetch(`/api/submissions/${id}`,action==='delete'?{method:'DELETE'}:{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:action})});if(r.ok)load(true);else setError('That action could not be completed.')}
async function bulk(){if(!selected.length||!confirm(`Delete ${selected.length} selected submission${selected.length>1?'s':''}?`))return;await fetch('/api/submissions/bulk',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected})});setSelected([]);load(true)}
if(checking)return <main className="admin-login"><span className="spinner"/><span>Opening staff area…</span></main>;if(!authed)return <main className="admin-login"><Brand/><form onSubmit={login}><span className="eyebrow">STAFF ONLY</span><h1>Control<br/><em>room.</em></h1><label>Staff passcode<input autoFocus inputMode="numeric" autoComplete="current-password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Enter passcode"/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" type="submit">Enter admin →</button><button className="text-btn" type="button" onClick={onBack}>Back to guest view</button></form></main>;
return <main className="admin"><header className="admin-head"><button className="back" onClick={onBack}><Icon name="back"/> Guest view</button><Brand/><button className="gallery-btn" onClick={onGallery}><Icon name="gallery"/> Live gallery</button></header><section className="admin-body"><div className="dash-title"><div><span className="eyebrow">STAFF CONTROL ROOM</span><h1>Tonight’s <em>SingShots</em></h1></div><CustomerQR/><div className="stats"><b>{items.filter(x=>x.status==='pending').length}</b><span>Pending in view</span></div></div><div className="toolbar"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><label>Media<select value={media} onChange={e=>setMedia(e.target.value)}><option value="all">Photos & videos</option><option value="image">Photos</option><option value="video">Videos</option></select></label><button disabled={!selected.length} className="danger" onClick={bulk}><Icon name="trash"/> Delete selected ({selected.length})</button><button className="refresh" onClick={()=>load()}>↻ Refresh</button></div>{error&&<div className="error" role="alert">{error}</div>}{loading?<div className="state"><span className="spinner"/>Loading the queue…</div>:items.length===0?<div className="state"><b>The stage is clear.</b><span>No submissions match these filters yet.</span></div>:<div className="submission-grid">{items.map(x=><article className="submission" key={x.id}><div className="thumb">{x.media_type==='video'?<video src={`/api/media/${x.id}`} controls preload="metadata"/>:<img src={`/api/media/${x.id}`} alt={x.caption||'Guest submission'}/>}<span className={`badge ${x.status}`}>{x.status}</span><label className="select"><input aria-label="Select submission" type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,x.id]:s.filter(i=>i!==x.id))}/></label></div><div className="card-info"><p>{x.caption||<span className="muted">No caption</span>}</p><small>{new Date(x.created_at+'Z').toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {x.media_type}</small><div className="card-actions"><button className="approve" onClick={()=>act(x.id,'approved')}>✓ Approve</button><button onClick={()=>act(x.id,'rejected')}>Reject</button><button className="icon-btn" aria-label="Delete" onClick={()=>act(x.id,'delete')}><Icon name="trash"/></button></div></div></article>)}</div>}</section></main>}
const galleryTag=(item:Item)=>{const text=(item.caption||'').toLowerCase();if(/\b(hen|bride|bridal)\b/.test(text))return'Hen Party';if(/\b(birthday|bday)\b/.test(text))return'Birthday';if(/\b(saturday|weekend)\b/.test(text))return'Saturday Night';if(/\b(love|wedding|engaged|anniversary)\b/.test(text))return'Love';return'Tonight'};
const galleryAlt=(item:Item)=>item.caption?`${item.caption} — guest moment at The London Karaoke Club`:`Guest karaoke celebration at The London Karaoke Club`;
function Gallery({onBack:_onBack}:{onBack:()=>void}){const [items,setItems]=useState<Item[]>([]);const [filter,setFilter]=useState('All');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch('/api/submissions?status=approved',{cache:'no-store'});if(!r.ok)throw new Error();const next=(await r.json()).submissions as Item[];if(active){setItems(next);setError('')}}catch{if(active)setError('The gallery is reconnecting…')}finally{if(active)setLoading(false)}};load();const poll=setInterval(load,10000);return()=>{active=false;clearInterval(poll)}},[]);
const tags=['All',...Array.from(new Set(items.map(galleryTag)))];const visible=filter==='All'?items:items.filter(item=>galleryTag(item)===filter);const mediaUrl=(id:string)=>`/api/media/${id}?gallery=1`;const imageItems=items.filter(item=>item.media_type==='image');const jsonLd={'@context':'https://schema.org','@type':'ImageGallery',name:'SingShot Live Wall of Fame',description:'Guest karaoke moments from The London Karaoke Club',image:imageItems.map(item=>({'@type':'ImageObject',contentUrl:typeof location==='undefined'?mediaUrl(item.id):`${location.origin}${mediaUrl(item.id)}`,caption:item.caption||'Guest karaoke celebration',dateCreated:item.created_at}))};const blur='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==';
return <main className="gallery-page">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <header className="gallery-page-header"><Brand/><div><span className="gallery-kicker">LIVE</span><h1>Wall of Fame</h1><p>Tonight’s loudest, brightest karaoke moments.</p></div></header>
  <nav className="gallery-filters" aria-label="Filter gallery">{tags.map(tag=><button key={tag} type="button" className={filter===tag?'active':''} aria-pressed={filter===tag} onClick={()=>setFilter(tag)}>{tag}<span>{tag==='All'?items.length:items.filter(item=>galleryTag(item)===tag).length}</span></button>)}</nav>
  {error&&<div className="gallery-notice" role="status">{error}</div>}
  <div className="gallery-layout">
    <section aria-live="polite" aria-busy={loading}>
      {loading?<div className="gallery-grid gallery-skeleton" aria-label="Loading gallery">{Array.from({length:6},(_,i)=><span key={i}/>)}</div>:visible.length===0?<div className="gallery-grid-empty"><Disco/><h2>No moments in this filter yet.</h2><p>Try another category or add yours from the upload link.</p></div>:<div className="gallery-masonry">{visible.map((item,index)=>{const tag=galleryTag(item);const date=new Date(`${item.created_at}Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});return <article className={`gallery-card ${index%7===0?'featured':index%5===0?'portrait':''}`} key={item.id}><div className="gallery-card-media">{item.media_type==='video'?<GalleryVideo src={mediaUrl(item.id)} caption={galleryAlt(item)}/>:<Image src={mediaUrl(item.id)} alt={galleryAlt(item)} fill sizes="(max-width: 560px) 100vw, (max-width: 900px) 50vw, (max-width: 1400px) 33vw, 25vw" loading={index<4?'eager':'lazy'} priority={index===0} placeholder="blur" blurDataURL={blur} unoptimized/>}<span className="gallery-card-tag">{tag}</span></div><div className="gallery-card-copy"><strong>{item.caption||'SingShot star moment'}</strong><time dateTime={item.created_at}>{date}</time></div></article>})}</div>}
    </section>
    <aside className="gallery-upload-card"><CustomerQR compact/><p>Scan to upload your photo or short video.</p><a href="/">Or tap here to upload your night →</a></aside>
  </div>
</main>}
