'use client';
import {useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';
type Item={id:string;media_type:'image'|'video';caption:string|null;status:'pending'|'approved'|'rejected';created_at:string};
const Icon=({name}:{name:'camera'|'upload'|'admin'|'gallery'|'check'|'back'|'trash'})=><span aria-hidden="true" className="icon">{{camera:'◉',upload:'↑',admin:'◆',gallery:'▦',check:'✓',back:'←',trash:'×'}[name]}</span>;
function Brand(){return <div className="brand" aria-label="SingShot"><b>SING</b><i>SHOT</i><small>THE LONDON KARAOKE CLUB</small></div>}
function Disco(){return <div className="disco-wrap" aria-hidden="true"><div className="disco"/><div className="beam b1"/><div className="beam b2"/></div>}
function CustomerQR({compact=false}:{compact?:boolean}){const [src,setSrc]=useState('');useEffect(()=>{QRCode.toDataURL(`${location.origin}/`,{width:compact?132:220,margin:1,color:{dark:'#10091c',light:'#fff9e9'}}).then(setSrc)},[compact]);return <div className={`customer-qr ${compact?'compact':''}`}>{src?<img src={src} alt="QR code to open SingShot on a phone"/>:<span className="qr-loading">Loading QR…</span>}<div><b>SCAN TO SINGSHOT</b><small>Open camera · Tap the link</small></div></div>}
export default function Home(){const [view,setView]=useState<'landing'|'capture'|'preview'|'success'|'admin'|'gallery'>('landing');const [file,setFile]=useState<File|null>(null);const [url,setUrl]=useState('');const [caption,setCaption]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
useEffect(()=>{const sync=()=>setView(location.pathname==='/staff'?'admin':location.pathname==='/gallery'?'gallery':'landing');sync();addEventListener('popstate',sync);return()=>removeEventListener('popstate',sync)},[]);
useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
function navigate(next:'landing'|'admin'|'gallery',path:string){history.pushState({},'',path);setView(next)}
function choose(f?:File){if(!f)return;setError('');if(!f.type.startsWith('image/')&&!f.type.startsWith('video/')){setError('Please choose a photo or video.');return}if(url)URL.revokeObjectURL(url);setFile(f);setUrl(URL.createObjectURL(f));setView('preview')}
async function submit(){if(!file)return;setBusy(true);setError('');const d=new FormData();d.set('media',file);d.set('caption',caption);d.set('consent',String(consent));try{const r=await fetch('/api/submissions',{method:'POST',body:d});const j=await r.json();if(!r.ok)throw new Error(j.error);setView('success')}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
function reset(){setFile(null);setUrl('');setCaption('');setConsent(false);setError('');navigate('landing','/')}
if(view==='admin')return <Admin onBack={()=>navigate('landing','/')} onGallery={()=>navigate('gallery','/gallery')}/>;
if(view==='gallery')return <Gallery onBack={()=>navigate('admin','/staff')}/>;
return <main className="guest"><header className="top"><Brand/><button className="admin-link" onClick={()=>navigate('admin','/staff')}><Icon name="admin"/> Admin</button></header>
{view==='landing'&&<section className="landing"><Disco/><div className="hero-copy"><p className="eyebrow">YOUR MOMENT. THEIR SCREEN.</p><h1>Sing it.<br/><em>Snap it.</em><br/>Share it.</h1><p className="intro">Capture your karaoke high note and join tonight’s live wall of fame.</p><button className="primary start" onClick={()=>setView('capture')}>Start SingShot <span>→</span></button><p className="micro">Photo or short video · Staff approved</p></div><CustomerQR compact/></section>}
{view==='capture'&&<section className="flow"><button className="back" onClick={()=>setView('landing')}><Icon name="back"/> Back</button><div className="panel"><span className="step">01 / CAPTURE</span><h1>Catch the<br/><em>moment.</em></h1><p>Take a photo, shoot a short clip, or pick one you already love.</p>{error&&<div className="error" role="alert">{error}</div>}<div className="capture-actions"><button className="capture-card pink" onClick={()=>{if(input.current){input.current.setAttribute('capture','environment');input.current.click()}}}><Icon name="camera"/><b>Open camera</b><small>Photo or short video</small></button><button className="capture-card purple" onClick={()=>{if(input.current){input.current.removeAttribute('capture');input.current.click()}}}><Icon name="upload"/><b>Choose a file</b><small>From your device</small></button></div><input ref={input} className="sr-only" aria-label="Choose photo or video" type="file" accept="image/jpeg,image/png,image/webp,image/heic,video/mp4,video/webm,video/quicktime" onChange={e=>choose(e.target.files?.[0])}/><p className="limits">Photos up to 12 MB · Videos up to 25 MB</p></div></section>}
{view==='preview'&&<section className="flow"><button className="back" onClick={()=>setView('capture')}><Icon name="back"/> Retake</button><div className="preview-grid"><div className="media-preview">{file?.type.startsWith('video/')?<video src={url} controls playsInline/>:<img src={url} alt="Your selected SingShot preview"/>}<span>PREVIEW</span></div><div className="panel preview-panel"><span className="step">02 / MAKE IT YOURS</span><h1>Looking<br/><em>iconic.</em></h1><label>Caption <small>OPTIONAL</small><textarea maxLength={160} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="What’s the anthem tonight?"/><span className="count">{caption.length}/160</span></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I'm happy for The London Karaoke Club to share this moment on its social channels. <small>Optional</small></span></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" disabled={busy} onClick={submit}>{busy?'Sending to the stage…':'Submit SingShot →'}</button></div></div></section>}
{view==='success'&&<section className="success"><div className="success-mark"><Icon name="check"/></div><span className="eyebrow">YOU'RE IN THE QUEUE</span><h1>That was<br/><em>electric.</em></h1><p>Your SingShot is with our crew. Once approved, it’ll light up the live gallery.</p><button className="primary" onClick={reset}>Capture another →</button><button className="text-btn" onClick={()=>navigate('gallery','/gallery')}>See the live gallery</button></section>}</main>}
function Admin({onBack,onGallery}:{onBack:()=>void;onGallery:()=>void}){const [items,setItems]=useState<Item[]>([]);const [status,setStatus]=useState('all');const [media,setMedia]=useState('all');const [selected,setSelected]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [authed,setAuthed]=useState(false);const [checking,setChecking]=useState(true);const [pin,setPin]=useState('');
async function load(silent=false){if(!silent)setLoading(true);try{const r=await fetch(`/api/submissions?status=${status}&media=${media}`,{cache:'no-store'});if(!r.ok)throw 0;setItems((await r.json()).submissions);setError('')}catch{setError('Could not refresh submissions.')}finally{setLoading(false)}}useEffect(()=>{if(!authed)return;load();const t=setInterval(()=>load(true),10000);return()=>clearInterval(t)},[status,media,authed]);
useEffect(()=>{fetch('/api/staff-session').then(r=>setAuthed(r.ok)).finally(()=>setChecking(false))},[]);
async function login(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/staff-login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});if(r.ok){setAuthed(true);setLoading(true);load()}else setError('That staff passcode is not correct.')}
async function act(id:string,action:'approved'|'rejected'|'delete'){const r=await fetch(`/api/submissions/${id}`,action==='delete'?{method:'DELETE'}:{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:action})});if(r.ok)load(true);else setError('That action could not be completed.')}
async function bulk(){if(!selected.length||!confirm(`Delete ${selected.length} selected submission${selected.length>1?'s':''}?`))return;await fetch('/api/submissions/bulk',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected})});setSelected([]);load(true)}
if(checking)return <main className="admin-login"><span className="spinner"/><span>Opening staff area…</span></main>;if(!authed)return <main className="admin-login"><Brand/><form onSubmit={login}><span className="eyebrow">STAFF ONLY</span><h1>Control<br/><em>room.</em></h1><label>Staff passcode<input autoFocus inputMode="numeric" autoComplete="current-password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Enter passcode"/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" type="submit">Enter admin →</button><button className="text-btn" type="button" onClick={onBack}>Back to guest view</button></form></main>;
return <main className="admin"><header className="admin-head"><button className="back" onClick={onBack}><Icon name="back"/> Guest view</button><Brand/><button className="gallery-btn" onClick={onGallery}><Icon name="gallery"/> Live gallery</button></header><section className="admin-body"><div className="dash-title"><div><span className="eyebrow">STAFF CONTROL ROOM</span><h1>Tonight’s <em>SingShots</em></h1></div><CustomerQR/><div className="stats"><b>{items.filter(x=>x.status==='pending').length}</b><span>Pending in view</span></div></div><div className="toolbar"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><label>Media<select value={media} onChange={e=>setMedia(e.target.value)}><option value="all">Photos & videos</option><option value="image">Photos</option><option value="video">Videos</option></select></label><button disabled={!selected.length} className="danger" onClick={bulk}><Icon name="trash"/> Delete selected ({selected.length})</button><button className="refresh" onClick={()=>load()}>↻ Refresh</button></div>{error&&<div className="error" role="alert">{error}</div>}{loading?<div className="state"><span className="spinner"/>Loading the queue…</div>:items.length===0?<div className="state"><b>The stage is clear.</b><span>No submissions match these filters yet.</span></div>:<div className="submission-grid">{items.map(x=><article className="submission" key={x.id}><div className="thumb">{x.media_type==='video'?<video src={`/api/media/${x.id}`} controls preload="metadata"/>:<img src={`/api/media/${x.id}`} alt={x.caption||'Guest submission'}/>}<span className={`badge ${x.status}`}>{x.status}</span><label className="select"><input aria-label="Select submission" type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,x.id]:s.filter(i=>i!==x.id))}/></label></div><div className="card-info"><p>{x.caption||<span className="muted">No caption</span>}</p><small>{new Date(x.created_at+'Z').toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {x.media_type}</small><div className="card-actions"><button className="approve" onClick={()=>act(x.id,'approved')}>✓ Approve</button><button onClick={()=>act(x.id,'rejected')}>Reject</button><button className="icon-btn" aria-label="Delete" onClick={()=>act(x.id,'delete')}><Icon name="trash"/></button></div></div></article>)}</div>}</section></main>}
function Gallery({onBack}:{onBack:()=>void}){const [items,setItems]=useState<Item[]>([]);const [cycle,setCycle]=useState(0);useEffect(()=>{const load=()=>fetch('/api/submissions?status=approved',{cache:'no-store'}).then(r=>r.json()).then(j=>setItems(j.submissions)).catch(()=>{});load();const poll=setInterval(load,8000),motion=setInterval(()=>setCycle(c=>c+1),12000);return()=>{clearInterval(poll);clearInterval(motion)}},[]);const ordered=items.length?[...items.slice(cycle%items.length),...items.slice(0,cycle%items.length)].slice(0,12):[];return <main className="gallery"><div className="gallery-glow"/><header><Brand/><span>LIVE WALL OF FAME</span><CustomerQR compact/><button onClick={onBack}>Staff</button></header>{ordered.length?<div key={cycle} className={`gallery-grid count-${Math.min(ordered.length,6)}`}>{ordered.map((x,i)=><figure style={{'--delay':`${i*90}ms`} as React.CSSProperties} key={x.id}>{x.media_type==='video'?<video src={`/api/media/${x.id}?gallery=1`} autoPlay muted loop playsInline/>:<img src={`/api/media/${x.id}?gallery=1`} alt=""/>}{x.caption&&<figcaption>{x.caption}</figcaption>}</figure>)}</div>:<div className="gallery-empty"><Disco/><h1>The stage is warming up.</h1><p>Scan the code. Take your shot. Own the screen.</p><CustomerQR/></div>}<footer><span>THE LONDON KARAOKE CLUB</span><b>•</b><span className="ticker">SING LOUD ✦ SHINE BRIGHT ✦ YOUR MOMENT, THEIR SCREEN</span></footer></main>}
