const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const fail=(message,status=400)=>json({error:message},status);
let venue={id:'london-karaoke-club',name:'SINGSHOT',sub_name:'at London Karaoke Club',logo_url:'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=200&q=80',primary_color:'#e5b842',accent_color:'#f59e0b',active_event_id:'evt-friday-night',wall_ticker_text:'🎤 SINGSHOT LIVE AT LONDON KARAOKE CLUB • SCAN QR TO SEE YOURSELF ON THE BIG SCREEN • TAG @LONDONKARAOKECLUB ON INSTAGRAM',auto_approve:false,qr_shape:'squircle'};
let events=[{id:'evt-friday-night',venue_id:'london-karaoke-club',title:'Friday Night Karaoke & Cocktails',event_type:'general',start_time:'2026-08-12T20:00:00Z',active:true,custom_notice:'Welcome to Soho’s premier VIP Karaoke experience!'}];
let rewards=[{id:'rew-free-shot',venue_id:'london-karaoke-club',title:'Free Tequila or Sambuca Shot',description:'Claim one complimentary shot at the main bar.',badge:'FREE SHOT 🍸',active:true},{id:'rew-2for1-cocktail',venue_id:'london-karaoke-club',title:'2-for-1 Signature Cocktails',description:'Buy one SingShot Special Cocktail and get one free.',badge:'2-FOR-1 COCKTAIL 🍹',active:true},{id:'rew-free-prosecco',venue_id:'london-karaoke-club',title:'Complimentary Glass of Prosecco',description:'Special celebration glass of prosecco on the house!',badge:'FREE PROSECCO 🥂',active:true}];
let submissions=[];
const sorted=list=>list.sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());
const db=(env)=>env.SUPABASE_URL&&env.SUPABASE_PUBLISHABLE_KEY?{url:env.SUPABASE_URL.replace(/\/$/,''),key:env.SUPABASE_PUBLISHABLE_KEY}:null;
async function dbFetch(env,path,init={}){const d=db(env);if(!d)throw new Error('Supabase is not configured');return fetch(`${d.url}${path}`,{...init,headers:{apikey:d.key,Authorization:`Bearer ${d.key}`,'content-type':'application/json',...(init.headers||{})}})}
function decodeDataUrl(value){const m=String(value||'').match(/^data:(image\/(?:jpeg|png|webp|gif));base64,(.+)$/);if(!m)throw new Error('Only base64 image data URLs are supported');const raw=atob(m[2]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return {mime:m[1],bytes};}
async function persistSubmission(env,next){const d=db(env);if(!d)return next;const image=decodeDataUrl(next.image_url),bucket=env.SUPABASE_PHOTOS_BUCKET||'singshot-photos',path=`submissions/${new Date().toISOString().slice(0,10)}/${next.id}.${image.mime.split('/')[1]}`;const upload=await dbFetch(env,`/storage/v1/object/${encodeURIComponent(bucket)}/${path}`,{method:'POST',headers:{'content-type':image.mime,'x-upsert':'false'},body:image.bytes});if(!upload.ok)throw new Error(`Photo upload failed (${upload.status})`);const publicUrl=`${d.url}/storage/v1/object/public/${bucket}/${path}`,row={...next,storage_path:path,image_url:publicUrl,original_image_url:publicUrl};const res=await dbFetch(env,'/rest/v1/singshot_submissions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});if(!res.ok)throw new Error(`Submission save failed (${res.status})`);return (await res.json())[0]||row;}
async function loadSubmissions(env,url){const d=db(env);if(!d)return null;const q=new URLSearchParams({select:'*',order:'created_at.desc'}),status=url.searchParams.get('status'),eventId=url.searchParams.get('event_id');if(status)q.set('status',`eq.${status}`);if(eventId)q.set('event_id',`eq.${eventId}`);const res=await dbFetch(env,`/rest/v1/singshot_submissions?${q}`);if(!res.ok)throw new Error(`Submission read failed (${res.status})`);return await res.json();}
export default{async fetch(request,env){const url=new URL(request.url),path=url.pathname;try{
if(path==='/api/health')return json({status:'ok',time:new Date().toISOString(),storage:Boolean(db(env))});
if(path==='/api/venue'&&request.method==='GET')return json(venue);
if(path==='/api/venue'&&request.method==='PUT'){venue={...venue,...await request.json()};return json(venue)}
if(path==='/api/events'&&request.method==='GET')return json(events);
if(path==='/api/events'&&request.method==='POST'){const body=await request.json(),next={id:`evt-${Date.now()}`,venue_id:venue.id,title:body.title||'Nightlife Event',event_type:body.event_type||'general',start_time:new Date().toISOString(),active:body.active??true,custom_notice:body.custom_notice};if(next.active){events=events.map(e=>({...e,active:false}));venue={...venue,active_event_id:next.id}}events.unshift(next);return json(next,201)}
if(path==='/api/rewards'&&request.method==='GET')return json(rewards.filter(r=>r.active));
if(path==='/api/rewards'&&request.method==='POST'){const body=await request.json(),next={id:`rew-${Date.now()}`,venue_id:venue.id,title:body.title,description:body.description,badge:body.badge||'SPECIAL OFFER 🎁',active:true};rewards.push(next);return json(next,201)}
if(path==='/api/submissions'&&request.method==='GET'){const remote=await loadSubmissions(env,url);return json(sorted(remote||[...submissions]))}
if(path==='/api/submissions'&&request.method==='POST'){const body=await request.json();if(!body.image_url||!body.occasion)return fail('Photo and occasion are required.');const first=typeof body.first_name==='string'&&body.first_name.trim()?body.first_name.trim():'VIP Guest',next={id:crypto.randomUUID(),event_id:body.event_id||venue.active_event_id,venue_id:venue.id,first_name:first,caption:body.caption||'',image_url:body.image_url,original_image_url:body.original_image_url||body.image_url,frame_style:body.frame_style||body.occasion.frame_style||'neon-gold',occasion:body.occasion,status:venue.auto_approve?'approved':'pending',created_at:new Date().toISOString(),featured:false},saved=await persistSubmission(env,next);if(!db(env))submissions.unshift(saved);return json(saved,201)}
const feature=path.match(/^\/api\/submissions\/([^/]+)\/feature$/);if(feature&&request.method==='POST'){const id=feature[1];if(db(env)){await dbFetch(env,'/rest/v1/singshot_submissions?featured=eq.true',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({featured:false})});const r=await dbFetch(env,`/rest/v1/singshot_submissions?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'approved',featured:true,featured_at:new Date().toISOString()})});if(!r.ok)return fail('Submission not found',404);return json((await r.json())[0])}const sub=submissions.find(s=>s.id===id);if(!sub)return fail('Submission not found',404);submissions.forEach(s=>s.featured=false);sub.status='approved';sub.featured=true;sub.featured_at=new Date().toISOString();return json(sub)}
const item=path.match(/^\/api\/submissions\/([^/]+)$/);if(item&&request.method==='PATCH'){const body=await request.json(),id=item[1];if(db(env)){const patch={};for(const k of ['status','featured','reward','claimed'])if(k in body)patch[k]=body[k];if(body.featured)Object.assign(patch,{status:'approved',featured_at:new Date().toISOString()});const r=await dbFetch(env,`/rest/v1/singshot_submissions?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});if(!r.ok)return fail('Submission not found',404);return json((await r.json())[0])}const idx=submissions.findIndex(s=>s.id===id);if(idx<0)return fail('Submission not found',404);Object.assign(submissions[idx],body);return json(submissions[idx])}
if(item&&request.method==='DELETE'){if(db(env)){const r=await dbFetch(env,`/rest/v1/singshot_submissions?id=eq.${item[1]}`,{method:'DELETE'});if(!r.ok)return fail('Submission not found',404)}else submissions=submissions.filter(s=>s.id!==item[1]);return json({success:true,id:item[1]})}
if(path.startsWith('/api/'))return fail('Not found',404);if(path==='/'||path==='/wall'||path==='/admin'||path==='/commercial'||path==='/submit')return env.ASSETS.fetch(new Request(`${url.origin}/index.html`,request));return env.ASSETS.fetch(request);
}catch(e){return fail('Service temporarily unavailable.',503)}}};
