const MIME=new Set(['image/jpeg','image/png','image/webp','image/heic','video/mp4','video/webm','video/quicktime']);
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const fail=(message,status=500)=>json({error:message},status);
const hex=buf=>[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('');
const sha1=async text=>hex(await crypto.subtle.digest('SHA-1',new TextEncoder().encode(text)));
const sha256=async text=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));
const adminToken=env=>sha256(`singshot-admin:${env.ADMIN_PIN||''}`);
async function isAdmin(request,env){if(!env.ADMIN_PIN)return false;const cookie=request.headers.get('cookie')||'',value=cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('singshot_admin='))?.slice(15);return value===await adminToken(env)}
const col=async(env,table,name)=>Boolean(await env.DB.prepare(`SELECT 1 FROM pragma_table_info('${table}') WHERE name=?`).bind(name).first());
const cloudConfig=env=>{if(!env.CLOUDINARY_CLOUD_NAME||!env.CLOUDINARY_API_KEY||!env.CLOUDINARY_API_SECRET)throw new Error('Cloudinary is not configured');return{cloud:env.CLOUDINARY_CLOUD_NAME,key:env.CLOUDINARY_API_KEY,secret:env.CLOUDINARY_API_SECRET}};
async function cloudUpload(env,file,id){const c=cloudConfig(env),timestamp=Math.floor(Date.now()/1000),folder='singshot',signature=await sha1(`folder=${folder}&public_id=${id}&timestamp=${timestamp}${c.secret}`),form=new FormData();form.set('file',file);form.set('api_key',c.key);form.set('timestamp',String(timestamp));form.set('folder',folder);form.set('public_id',id);form.set('signature',signature);const res=await fetch(`https://api.cloudinary.com/v1_1/${c.cloud}/auto/upload`,{method:'POST',body:form});if(!res.ok)throw new Error('Cloudinary upload failed');return await res.json()}
async function cloudDelete(env,publicId,resourceType){const c=cloudConfig(env),timestamp=Math.floor(Date.now()/1000),signature=await sha1(`invalidate=true&public_id=${publicId}&timestamp=${timestamp}${c.secret}`),form=new FormData();form.set('public_id',publicId);form.set('timestamp',String(timestamp));form.set('invalidate','true');form.set('api_key',c.key);form.set('signature',signature);await fetch(`https://api.cloudinary.com/v1_1/${c.cloud}/${resourceType}/destroy`,{method:'POST',body:form})}
let schemaReady;
const ensureSchema=env=>schemaReady??=(async()=>{await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS submissions (id TEXT PRIMARY KEY,venue_id TEXT NOT NULL DEFAULT 'lkc',event_id TEXT NOT NULL DEFAULT 'tonight',media_key TEXT NOT NULL UNIQUE,media_type TEXT NOT NULL CHECK(media_type IN ('image','video')),first_name TEXT,caption TEXT,occasion_type TEXT NOT NULL DEFAULT 'star',occasion_label TEXT,occasion_detail TEXT,share_consent INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,approved_at TEXT,featured INTEGER NOT NULL DEFAULT 0,featured_at TEXT,reward_id TEXT,reward_title TEXT,is_shared INTEGER NOT NULL DEFAULT 0)"),env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_submissions_status_created ON submissions(status,created_at DESC)'),env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_submissions_event_status ON submissions(event_id,status,created_at DESC)'),env.DB.prepare("CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS venues (id TEXT PRIMARY KEY,name TEXT NOT NULL,logo TEXT,branding TEXT,settings TEXT)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY,venue_id TEXT NOT NULL,title TEXT NOT NULL,event_type TEXT,start_time TEXT,end_time TEXT,active INTEGER NOT NULL DEFAULT 1,branding TEXT)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS rewards (id TEXT PRIMARY KEY,venue_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT,active INTEGER NOT NULL DEFAULT 1)")]);
for(const [table,name,sql] of [['submissions','venue_id',"ALTER TABLE submissions ADD COLUMN venue_id TEXT NOT NULL DEFAULT 'lkc'"],['submissions','event_id',"ALTER TABLE submissions ADD COLUMN event_id TEXT NOT NULL DEFAULT 'tonight'"],['submissions','first_name','ALTER TABLE submissions ADD COLUMN first_name TEXT'],['submissions','occasion_type',"ALTER TABLE submissions ADD COLUMN occasion_type TEXT NOT NULL DEFAULT 'star'"],['submissions','occasion_label','ALTER TABLE submissions ADD COLUMN occasion_label TEXT'],['submissions','occasion_detail','ALTER TABLE submissions ADD COLUMN occasion_detail TEXT'],['submissions','featured','ALTER TABLE submissions ADD COLUMN featured INTEGER NOT NULL DEFAULT 0'],['submissions','featured_at','ALTER TABLE submissions ADD COLUMN featured_at TEXT'],['submissions','reward_id','ALTER TABLE submissions ADD COLUMN reward_id TEXT'],['submissions','reward_title','ALTER TABLE submissions ADD COLUMN reward_title TEXT']]){if(!(await col(env,table,name)))await env.DB.prepare(sql).run()}
await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO venues (id,name,logo,branding,settings) VALUES ('lkc','London Karaoke Club','/london-karaoke-club-badge-v2.webp','{\"accent\":\"#ffe23b\",\"background\":\"#10091c\"}','{\"qr\":\"/\",\"wallMode\":\"live\"}')"),env.DB.prepare("INSERT OR IGNORE INTO events (id,venue_id,title,event_type,active) VALUES ('tonight','lkc','Tonight at London Karaoke Club','open',1)"),env.DB.prepare("INSERT OR IGNORE INTO rewards (id,venue_id,title,description,active) VALUES ('free-shot','lkc','FREE SHOT','Show this screen to the bar',1),('two-for-one','lkc','2-FOR-1 COCKTAIL','Available tonight only',1),('birthday-prosecco','lkc','FREE BIRTHDAY PROSECCO','For birthday SingShots',1),('cloakroom','lkc','FREE CLOAKROOM','Tonight only',1)")]);
})().catch(e=>{schemaReady=undefined;throw e});
export default {async fetch(request,env){
  const url=new URL(request.url);const path=url.pathname;
  try{
    if(path==='/api/staff-login'&&request.method==='POST'){const {pin}=await request.json();if(!env.ADMIN_PIN||String(pin)!==String(env.ADMIN_PIN))return fail('Incorrect passcode.',401);const token=await adminToken(env);return new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json','set-cookie':`singshot_admin=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`}})}
    if(path==='/api/staff-session')return (await isAdmin(request,env))?json({ok:true}):fail('Staff sign-in required.',401);
    if(path.startsWith('/api/'))await ensureSchema(env);
    if(path==='/api/submissions'&&request.method==='GET'){
      const where=[],vals=[];const status=url.searchParams.get('status'),media=url.searchParams.get('media');
      if(status!=='approved'&&!(await isAdmin(request,env)))return fail('Staff sign-in required.',401);
      if(status&&status!=='all'){where.push('status = ?');vals.push(status)}if(media&&media!=='all'){where.push('media_type = ?');vals.push(media)}
      const q=`SELECT * FROM submissions ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY created_at DESC LIMIT 250`;
      const out=await env.DB.prepare(q).bind(...vals).all();return json({submissions:out.results});
    }
    if(path==='/api/settings/auto-approve'&&request.method==='GET'){if(!(await isAdmin(request,env)))return fail('Staff sign-in required.',401);const row=await env.DB.prepare("SELECT value FROM app_settings WHERE key='auto_approve'").first();return json({enabled:row?.value==='1'})}
    if(path==='/api/settings/auto-approve'&&request.method==='PATCH'){if(!(await isAdmin(request,env)))return fail('Staff sign-in required.',401);const {enabled}=await request.json();if(typeof enabled!=='boolean')return fail('Choose whether auto approve is on or off.',400);await env.DB.prepare("INSERT INTO app_settings (key,value,updated_at) VALUES ('auto_approve',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(enabled?'1':'0').run();return json({enabled})}
    if(path==='/api/submissions'&&request.method==='POST'){
      const data=await request.formData(),file=data.get('media');if(!(file instanceof File))return fail('Choose a photo or video.',400);
      if(!MIME.has(file.type)||!file.type.startsWith('image/'))return fail('Use a JPG, PNG, WebP, or HEIC photo.',415);
      const kind='image';if(file.size>12582912)return fail('Photos must be under 12 MB.',413);
      const firstName=String(data.get('first_name')||'').trim().slice(0,40);if(!firstName)return fail('Add your first name.',400);
      const caption=String(data.get('caption')||'').trim().slice(0,90),consent=data.get('consent')==='true';if(!consent)return fail('Please consent to appear on the venue screens.',400);
      const allowed=new Set(['star','birthday','hen','corporate','fun']),rawOccasion=String(data.get('occasion_type')||'star'),occasion=allowed.has(rawOccasion)?rawOccasion:'star',occasionLabel=String(data.get('occasion_label')||'').trim().slice(0,48)||null,occasionDetail=String(data.get('occasion_detail')||'').trim().slice(0,48)||null;
      const id=crypto.randomUUID(),publicId=`singshot/${id}`,setting=await env.DB.prepare("SELECT value FROM app_settings WHERE key='auto_approve'").first(),autoApprove=setting?.value==='1',submissionStatus=autoApprove?'approved':'pending';
      await cloudUpload(env,file,id);
      try{await env.DB.prepare("INSERT INTO submissions (id,venue_id,event_id,media_key,media_type,first_name,caption,occasion_type,occasion_label,occasion_detail,share_consent,status,created_at,approved_at,featured,reward_id,reward_title,is_shared) VALUES (?,'lkc','tonight',?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CASE WHEN ?='approved' THEN CURRENT_TIMESTAMP ELSE NULL END,0,NULL,NULL,CASE WHEN ?='approved' THEN 1 ELSE 0 END)").bind(id,publicId,kind,firstName,caption||null,occasion,occasionLabel,occasionDetail,1,submissionStatus,submissionStatus,submissionStatus).run()}catch(e){await cloudDelete(env,publicId,kind);throw e}return json({id,status:submissionStatus},201);
    }
    const match=path.match(/^\/api\/submissions\/([^/]+)$/);
    if(match&&request.method==='PATCH'){if(!(await isAdmin(request,env)))return fail('Staff sign-in required.',401);const body=await request.json();if(body.featured===true){await env.DB.prepare('UPDATE submissions SET featured=0 WHERE featured=1').run();await env.DB.prepare("UPDATE submissions SET featured=1,featured_at=CURRENT_TIMESTAMP,status='approved',approved_at=COALESCE(approved_at,CURRENT_TIMESTAMP),is_shared=share_consent WHERE id=?").bind(match[1]).run();return json({ok:true})}if(body.featured===false){await env.DB.prepare('UPDATE submissions SET featured=0,featured_at=NULL WHERE id=?').bind(match[1]).run();return json({ok:true})}if(typeof body.reward_title==='string'){await env.DB.prepare('UPDATE submissions SET reward_id=?,reward_title=? WHERE id=?').bind(body.reward_id||'custom',body.reward_title.trim().slice(0,60)||null,match[1]).run();return json({ok:true})}const {status}=body;if(!['approved','rejected'].includes(status))return fail('Invalid status.',400);await env.DB.prepare("UPDATE submissions SET status=?, approved_at=CASE WHEN ?='approved' THEN CURRENT_TIMESTAMP ELSE NULL END, is_shared=CASE WHEN ?='approved' THEN share_consent ELSE 0 END, featured=CASE WHEN ?='rejected' THEN 0 ELSE featured END WHERE id=?").bind(status,status,status,status,match[1]).run();return json({ok:true})}
    if(match&&request.method==='DELETE'){if(!(await isAdmin(request,env)))return fail('Staff sign-in required.',401);const row=await env.DB.prepare('SELECT media_key,media_type FROM submissions WHERE id=?').bind(match[1]).first();if(row){await cloudDelete(env,row.media_key,row.media_type);await env.DB.prepare('DELETE FROM submissions WHERE id=?').bind(match[1]).run()}return json({ok:true})}
    if(path==='/api/submissions/bulk'&&request.method==='DELETE'){if(!(await isAdmin(request,env)))return fail('Staff sign-in required.',401);const body=await request.json(),ids=Array.isArray(body.ids)?body.ids.filter(x=>typeof x==='string').slice(0,250):[];if(!ids.length)return fail('Select at least one item.',400);const marks=ids.map(()=>'?').join(','),rows=await env.DB.prepare(`SELECT media_key,media_type FROM submissions WHERE id IN (${marks})`).bind(...ids).all();await Promise.all(rows.results.map(r=>cloudDelete(env,r.media_key,r.media_type)));await env.DB.prepare(`DELETE FROM submissions WHERE id IN (${marks})`).bind(...ids).run();return json({ok:true})}
    const mediaMatch=path.match(/^\/api\/media\/([^/]+)$/);
    if(mediaMatch&&request.method==='GET'){const gallery=url.searchParams.get('gallery')==='1';if(!gallery&&!(await isAdmin(request,env)))return fail('Staff sign-in required.',401);const row=await env.DB.prepare(`SELECT * FROM submissions WHERE id=? ${gallery?"AND status='approved'":''}`).bind(mediaMatch[1]).first();if(!row)return new Response('Not found',{status:404});const c=cloudConfig(env),asset=await fetch(`https://res.cloudinary.com/${c.cloud}/${row.media_type}/upload/${row.media_key}`);if(!asset.ok)return new Response('Not found',{status:404});const h=new Headers({'content-type':asset.headers.get('content-type')||'application/octet-stream','cache-control':gallery?'private, max-age=30':'private, no-store','content-disposition':'inline','x-content-type-options':'nosniff'});return new Response(asset.body,{headers:h})}
    if(path==='/gallery')return env.ASSETS.fetch(new Request(`${url.origin}/gallery/`,request));
    if(['/staff','/submit','/wall'].includes(path))return env.ASSETS.fetch(new Request(`${url.origin}/`,request));
    return env.ASSETS.fetch(request);
  }catch(e){return fail(path.startsWith('/api/')?'Storage is temporarily unavailable.':'Service unavailable.',503)}
}};
